apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-green
spec:
  selector:
    matchLabels:
      app: gateway
      version: green
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
        version: green
    spec:
      containers:
        - name: gateway-service
          image: CONTAINER_IMAGE_GREEN
          #image: 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/cloud-gateway:latest
          envFrom:
            - configMapRef:
                name: petclinic-config