apiVersion: v1
kind: Service
metadata:
  name: gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # 내부 NLB를 생성
spec:
  selector:
    app: gateway
    version: blue
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
