apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-blue
spec:
  selector:
    matchLabels:
      app: gateway
      version: blue
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
        version: blue
    spec:
      containers:
        - name: gateway-service
          image: CONTAINER_IMAGE_BLUE
          #image: 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/cloud-gateway:latest
          envFrom:
            - configMapRef:
                name: petclinic-config