apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-blue
spec:
  selector:
    matchLabels:
      app: customers
      version: blue
  replicas: 2
  template:
    metadata:
      labels:
        app: customers
        version: blue
    spec:
      containers:
        - name: customers
          image: CONTAINER_IMAGE_BLUE
          envFrom:
            - configMapRef:
                name: petclinic-config