apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: promtail-pods-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]



---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promtail-pods-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: promtail-pods-reader
  apiGroup: rbac.authorization.k8s.io

