apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: logging
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://k8s-loki-loki-259bc06d68-5e9d20f88ff3f869.elb.ap-northeast-2.amazonaws.com:3100/loki/api/v1/push
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: ['__meta_kubernetes_pod_annotation_prometheus_io_scrape']
            action: keep
            regex: 'true'
          - source_labels: ['__meta_kubernetes_pod_annotation_prometheus_io_path']
            action: replace
            target_label: '__metrics_path__'
            regex: '(.+)'
          - source_labels: ['__address__', '__meta_kubernetes_pod_annotation_prometheus_io_port']
            action: replace
            regex: '([^:]+)(?::\d+)?;(\d+)'
            replacement: '$1:$2'
            target_label: '__address__'
          - action: labelmap
            regex: '__meta_kubernetes_pod_label_(.+)'
          - source_labels: ['__meta_kubernetes_namespace']
            action: replace
            target_label: 'namespace'
          - source_labels: ['__meta_kubernetes_pod_name']
            action: replace
            target_label: 'pod_name'
