apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: logging 
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      containers:
      - name: promtail
        image: grafana/promtail:latest
        args:
          - "-config.file=/etc/promtail/promtail.yaml"
        volumeMounts:
          - name: promtail-config
            mountPath: /etc/promtail
         
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
       
