apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-blue
spec:
  selector:
    matchLabels:
      app: visits
      version: blue
  replicas: 2
  template:
    metadata:
      labels:
        app: visits
        version: blue
    spec:
      containers:
        - name: visits
          image: CONTAINER_IMAGE_BLUE
          envFrom:
            - configMapRef:
                name: petclinic-config